config/routes.rb
Rails.application.routes.draw do
  get "content/index"
  resources :images
  resources :videos
  resources :audios
  get "users/dashboard"
  get "password_resets/new"
  get "password_resets/edit"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  root "home#index"
  resources :users do
    member do
      get :subscriptions, :subscribers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  mount API::Base, at: "/"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/audio.rb
class Audio < ApplicationRecord
  mount_uploader :file, AudioUploader
  belongs_to :user
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  before_action :set_audio, only: [:show, :edit, :update, :destroy]

  # GET /audios
  # GET /audios.json
  def index
    @audios = Audio.all
  end

  # GET /audios/1
  # GET /audios/1.json
  def show
  end

  # GET /audios/new
  def new
    @audio = current_user.audios.build
  end

  # GET /audios/1/edit
  def edit
  end

  # POST /audios
  # POST /audios.json
  def create
    @audio = current_user.audios.build(audio_params)

    respond_to do |format|
      if @audio.save
        format.html { redirect_to @audio, notice: "Audio was successfully created." }
        format.json { render :show, status: :created, location: @audio }
      else
        format.html { render :new }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audios/1
  # PATCH/PUT /audios/1.json
  def update
    respond_to do |format|
      if @audio.update(audio_params)
        format.html { redirect_to @audio, notice: "Audio was successfully updated." }
        format.json { render :show, status: :ok, location: @audio }
      else
        format.html { render :edit }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audios/1
  # DELETE /audios/1.json
  def destroy
    @audio.destroy
    respond_to do |format|
      format.html { redirect_to audios_url, notice: "Audio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_audio
    @audio = Audio.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def audio_params
    params.require(:audio).permit(:title, :file)
  end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/views/audios/_audio.html.erb
<p>
  <strong>Title:</strong>
  <%= audio.title %>
</p>
<p>
  <audio controls width="300" height="180" src="<%= audio.file %>"></audio>
</p>

app/views/audios/_form.html.erb
<%= simple_form_for(@audio) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.file_field :file %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/audios/edit.html.erb
<h1>Editing Audio</h1>

<%= render 'form', audio: @audio %>

<%= link_to 'Show', @audio %> |
<%= link_to 'Back', audios_path %>

app/views/audios/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Audios</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @audios.each do |audio| %>
      <tr>
        <td><%= audio.title %></td>
        <td>
          <audio controls src="<%= audio.file %>"></audio>
        </td>
        <td><%= link_to 'Show', audio %></td>
        <td><%= link_to 'Edit', edit_audio_path(audio) %></td>
        <td><%= link_to 'Destroy', audio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Audio', new_audio_path %>

app/views/audios/new.html.erb
<h1>New Audio</h1>

<%= render 'form', audio: @audio %>

<%= link_to 'Back', audios_path %>

app/views/audios/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @audio.title %>
</p>
<p>
  <strong>File:</strong>
  <audio controls src="<%= @audio.file %>"></audio>
</p>
<%= link_to 'Edit', edit_audio_path(@audio) %> |
<%= link_to 'Back', audios_path %>