config/routes.rb
Rails.application.routes.draw do
  get "content/index"
  resources :images
  resources :videos
  resources :audios
  get "users/dashboard"
  get "password_resets/new"
  get "password_resets/edit"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  root "home#index"
  resources :users do
    member do
      get :subscriptions, :subscribers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  mount API::Base, at: "/"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :file, VideoUploader
  belongs_to :user
end

app/controllers/api/v1/videos.rb
module API
  module V1
    class Videos < Grape::API
      include API::V1::Defaults
      resource :videos do
        desc "Return all Videos"
        get "" do
          Video.all
        end
        desc "Return a Video"
        params do
          requires :id, type: String, desc: "ID of the Video"
        end
        get ":id" do
          Video.where(id: permitted_params[:id]).first!
        end
      end
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = current_user.videos.build
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.build(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def video_params
    params.require(:video).permit(:title, :file)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= simple_form_for(@video) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.file_field :file %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div class="col-lg-3 col-md-4 col-6 vcard">
  <%= link_to video do %>
    <p>
      <video controls src="<%= video.file.url if video.file?  %>"></video>
    </p>
    <p><%= video.title.capitalize %>
      <% if current_user?(video.user)%>
        | <%= link_to 'Edit', edit_video_path(video) %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Videos</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td>
          <video controls width="640" height="480" src="<%= video.file.url if video.file?  %>"></video>
        </td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<div class="container-fluid">
  <div class="row mt-3">
    <div class="col-md-9">
      <div class="vcontainer">
        <video controls src="<%= @video.file.url if @video.file? %>"></video>
      </div>
      <p>
        <strong>Title:</strong>
        <%= @video.title %>
      </p>
      <hr>
    </div>
    <div class="col-md-3">
      <div class="card">
        <%= gravatar_for @video.user, class: "card-img-top" %>
        <div class="card p-3">
          <h5 class="card-title"><%= link_to @video.user.name.capitalize, @video.user %></h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <p class="bg-primary text-white p-3">Subcribers <%= @video.user.subscribers.count %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>