config/routes.rb
Rails.application.routes.draw do
  get "content/index"
  resources :images
  resources :videos
  resources :audios
  get "users/dashboard"
  get "password_resets/new"
  get "password_resets/edit"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  root "home#index"
  resources :users do
    member do
      get :subscriptions, :subscribers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  mount API::Base, at: "/"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zimcreative</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="notification bg-info global-notification p-2 text-light text center">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification bg-warning global-notification p-2 text-light text center">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Zimcreative", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "TV", '/content/index', class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Channels", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <% if user_signed_in? %>
                <%= link_to 'Dashboard', users_dashboard_path, class: "dropdown-item" %>
                <%= link_to "Profile", current_user, class: "dropdown-item" %>
                <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
              <% else %>
                <%= link_to "Log in", login_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>